#application config
app:
  name: thoughtware-hadess-ee
  path: ${APP_HOME}
  version: ee

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
#web config
server:
  port: 8080

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5441/hadess_ce?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: hadess_ce
  db:
    port: 5441
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#eas config
eas:
  embbed:
    enable: true
base:
  url: http://192.168.10.9:8080

DATA_HOME: /opt/thoughtware/hadess


#dfs config
dfs:
  server:
    enabled: true
    mode: server
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4001
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5001
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: true
    mode: server
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6001
    bucket: ${app.name}


#plugin config
plugin.path: ${APP_HOME}/plugin


homes:
  address: http://139.196.76.221:8080


#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

#file
file:
  path: http://file.tiklab.net

repository:
  address: ${DATA_HOME}/repository

backups:
  time: 0 0 2 * * ?
  dir: ${DATA_HOME}
  xpack:
    dir: /Users/limingliang/tiklab/tiklab-xpack-ee/repository
  pgsql:
    dir: /Users/limingliang/postgreSQL/bin