#application config
app:
  name: hadess


spring:
  profiles:
    active: demo

#web config
server:
  port: 8080
  tomcat:
    max-threads: 200       # 最大线程数
    max-connections: 10000 # 最大连接数
    accept-count: 100      # 等待队列长度

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/hadess

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/thoughtware_hadess?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: thoughtware_hadess
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#soular config
soular:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

base:
  url: http://eas-ce.demo.tiklab.net

#licences config
licences:
  path: ${DATA_HOME}/licences



repository:
  address: ${DATA_HOME}/repository

visible:
  address: ""


backups:
  time: 0 0 2 * * ?
  dir: /data/backup
  xpack:
    dir: ${DATA_HOME}/repository

openscan_mvn:
  repo: http://172.13.1.24:8080/repository/maven-public
  user: admin
  password: 123456

