#application config
app:
  name: thoughtware-hadess
  path: ${APP_HOME}
  version: ee

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
#web config
server:
  port: 8083

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5583/hadess_public?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: hadess_public
  db:
    port: 5583
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#eas config
eas:
  embbed:
    enable: true

DATA_HOME: /opt/thoughtware/hadess-public

base:
  url: http://e.hadess.thoughtware.cn

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4083
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: ture
    mode: server
    port: 5083
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6083
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}


#plugin config
plugin.path: ${APP_HOME}/plugin


homes:
  address: http://homes.thoughtware.cn


#licences config
licences:
  path: ${DATA_HOME}/licences

#file
file:
  path: http://file.thoughtware.net

repository:
  address: ${DATA_HOME}/repository



backups:
  time: 0 0 2 * * ?
  dir: /data/backup


openscan_mvn:
  repo: http://172.13.1.24:8080/repository/maven-public
  user: admin
  password: 123456