#application config
app:
  name: thoughtware-hadess
  path: ${APP_HOME}
spring:
  profiles:
    active: demo

#web config
server:
  port: 8080

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/xpack?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: xpack
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net


DATA_HOME: /opt/tiklab/xpack

base:
  url: http://eas-ce.demo.tiklab.net

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
homes:
  address: http://172.11.1.11:8080

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

#file
file:
  path: http://file.dev.tiklab.net

repository:
  address: ${DATA_HOME}/repository


backups:
  time: 0 0 2 * * ?
  dir: /data
  xpack:
    dir: ${DATA_HOME}/repository


openscan_mvn:
  repo: http://172.13.1.24:8080/repository/maven-public
  user: admin
  password: 123456