#application config
app:
  name: thoughtware-hadess
  path: ${APP_HOME}
  version: ce

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
#web config
server:
  port: 8080

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/thoughtware_hadess?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: thoughtware_hadess
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#eas config
eas:
  embbed:
    enable: false
  address: http://gittok-ce.demo.thoughtware.cn

DATA_HOME: /opt/tiklab/thoughtware_hadess

base:
  url: http://gittok-ce.demo.thoughtware.cn

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}


#plugin config
plugin.path: ${APP_HOME}/plugin


homes:
  address: http://homes.thoughtware.cn


#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

#file
file:
  path: http://file.thoughtware.net

repository:
  address: ${DATA_HOME}/repository



backups:
  time: 0 0 2 * * ?
  dir: /data/backup
  xpack:
    dir: ${DATA_HOME}/repository

openscan_mvn:
  repo: http://172.13.1.24:8080/repository/maven-public
  user: admin
  password: 123456