#application config
app:
  name: hadess


#web config
server:
  port: 8080
  tomcat:
    max-threads: 200       # 最大线程数
    max-connections: 10000 # 最大连接数
    accept-count: 100      # 等待队列长度


APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/thoughtware-hadess

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_xpack?currentSchema=public&stringtype=unspecified
  username: postgres
  #driverClassName: com.mysql.cj.jdbc.Driver
  #url: jdbc:mysql://172.10.1.10:3306/tiklab_hadess?characterEncoding=utf8&useSSL=false
  #username: root
  password: darth2020


postgresql:
  embbed:
    enable: false
  database: thoughtware_hadess
  type: local

#dcs config
dcs:
  server:
    enabled: true
    port: 5002
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5002
    group: g1
    database: dcs1
    expire: 6000


#  (local:本地登录  soular:统一登录)
auth:
  type: local
  soular:
    address: http://192.168.10.15:8080

external:
  url: http://192.168.10.9:3030


#repositroy config
repository:
  address: ${DATA_HOME}/repository

visible:
  address: ""



