#application config
app:
  name: hadess


spring:
  profiles:
    active: dev

#web config
server:
  port: 8080
  tomcat:
    max-threads: 200       # 最大线程数
    max-connections: 10000 # 最大连接数
    accept-count: 100      # 等待队列长度

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/thoughtware-hadess

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_xpack?currentSchema=public&stringtype=unspecified
  username: postgres
  #driverClassName: com.mysql.cj.jdbc.Driver
  #url: jdbc:mysql://172.10.1.10:3306/tiklab_hadess?characterEncoding=utf8&useSSL=false
  #username: root
  password: darth2020


postgresql:
  embbed:
    enable: false
  database: thoughtware_hadess
  type: local

#dcs config
dcs:
  server:
    enabled: true
    port: 5002
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5002
    group: g1
    database: dcs1
    expire: 6000

#soular config
soular:
  embbed:
    enable: true


base:
  url: http://192.168.10.9:3030

#licences config
licences:
  path: ${DATA_HOME}/licences


#repositroy config
repository:
  address: ${DATA_HOME}/repository

visible:
  address: ""


backups:
  time: 0 0 2 * * ?
  dir:  ${DATA_HOME}/backups
  xpack:
    dir: ${DATA_HOME}/repository

openscan_mvn:
  repo: http://172.13.1.24:8080/repository/maven-public
  user: admin
  password: 123456

postin:
  scan:
    package: io.tiklab.hadess


