#application config
app:
  name: tiklab-hadess



server:
  port: 8080
  tomcat:
    max-threads: 200       # 最大线程数
    max-connections: 10000 # 最大连接数
    accept-count: 100      # 等待队列长度

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/${app.name}


#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/thoughtware_hadess?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: thoughtware_hadess
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200


#  (local:本地登录  soular:统一登录)
auth:
  type: soular
  soular:
    address: http://e.tiklab.net

external:
  url: http://e.tiklab.net

repository:
  address: ${DATA_HOME}/repository



visible:
  address: http://e.hadess.tiklab.net

