#application config
app:
  name: thoughtware-hadess-public


#web config
server:
  port: 8083

APP_HOME: ${APP_HOME}

DATA_HOME: /opt/tiklab/hadess_public

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5483/hadess_public?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: hadess_public
  db:
    port: 5483
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


#dcs config
dcs:
  server:
    enabled: true
    port: 8000
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:8000
    group: g1
    database: dcs1
    expire: 6000


auth:
  type: local


external:
  url: https://mirror.tiklab.net

