#application config
app:
  name: hadess


spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  profiles:
    active: prd

#web config
server:
  port: 8080


APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/hadess

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5441/hadess?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: hadess
  db:
    port: 5441
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200


#eas config
soular:
  embbed:
    enable: true

message:
  sms:
    enabled: true


base:
  url: http://192.168.10.9:8080

#licences config
licences:
  path: ${DATA_HOME}/licences


repository:
  address: ${DATA_HOME}/repository

visible:
  address: ""


backups:
  time: 0 0 2 * * ?
  dir: ${DATA_HOME}
  xpack:
    dir: ${DATA_HOME}/repository

postin:
  scan:
    package: io.tiklab.hadess